name: Build docker image and push to ghcr.io
on:
    release:
        types: [published]

permissions:
    contents: read
    packages: write

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build
        steps:
        - name: 🔔 Checkout Code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: 🔧 Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.21'
            cache: false

        - name: ✨ Login to GitHub Container Registry
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        - name: ✨ Build Docker Image
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ghcr.io/${{ github.repository }}/wisp:${{ github.ref_name }}
