name: PR Checks
on:
  push:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: 🔔 Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔧 Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false

      - name: 📦 Install and generate prisma client
        run: |
          go mod download
          go run github.com/steebchen/prisma-client-go prefetch
          go run github.com/steebchen/prisma-client-go generate

      - name: ✨ golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
